### ISSUE TITLE
no more instructions on alpha feed

### ISSUE THREAD

**Issue by kristinoberhaus** [tgaillar/OpenSSL-Updater#1]
I am trying to get gmail to work on my phone.  Everything points to this update.  I don't have Alpha-apps on my preware and every follow me link for instructions takes you to a page with no text.

Please help.  I really don't want to have to switch phones for an email issue.  My job's email system is on google suite, so I really need this .

Thanks

PS -- I can install through WebOS QuickInstall if that would help.

**Comment by tgaillar** [comment]
This is most likely the alpha feeds page you are looking for: http://webos-internals.org/index.php?title=Testing_Feeds

Then there is also this page by Alan Morford that may come (very) handy: https://pivotce.com/2016/07/07/guide-fixing-google-synergy/

Please keep in mind the updater is still alpha for a reason (it would have gone to production otherwise). You might be good (and lucky?), though. If not, don't Doctor the device and get back here, there is a way to recover & finish the installation (done it once remotely, see more in the OpenSSL-Updater thread on the Webosnation forum).

**Comment by kristinoberhaus** [comment]
Thank -- this took care of it!!!!
 

Sent: Tuesday, February 21, 2017 at 11:45 AM

**Comment by tgaillar** [comment]
Thanks for the feedback, glad it helped you do the trick! :)
